baseURL = "https://www.hannes-lehmann.com/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Hannes Lehmann · Solution Architect, Developer and Consultant, all-around tech enthusiast"
theme = "hale-custom-hugo-theme"


# Languages
#   en
#     weight: 1
#   es
#     weight: 2

[build]
  writeStats = true
  
# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
 

# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "index.html#about"
  weight = 2

  [[menu.header]]
  name = "Experience"
  URL = "index.html#experience"
  weight = 3

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 4


  [[menu.footer]]
  name = "About"
  URL = "index.html#about"
  weight = 2


  #[[menu.footer]]
  #name = "📚 Books"
  #URL = "/books"
  #weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "index.html#contact"
  weight = 5

  [[menu.footer]]
  name = "Impress"
  URL = "/impress"
  weight = 7


[params]

  sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]
  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager
  homepageExperienceCount = 6

  [params.logo]
    text1 = "Hannes"
    text2 = "Lehmann"

   [params.footer]
      copyright = "© hannes-lehmann.com // based on Hugo theme by Adrián Moreno Peña."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"

[taxonomies]
  book_author = "book_authors"
  book_category = "book_categories"
