# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "HannesLehmann-Free-Hugo-Theme"
license = "MIT"
licenselink = "https://github.com/hannes-lehmann/hale-hugo-theme/blob/main/LICENSE"
description = "Minimalistic and clean theme for Hugo, great for Single Page personal websites"
homepage = "https://github.com/hannes-lehmann/hale-hugo-theme"
demosite = "https://hannes-lehmann.com/"

tags = ["responsive", "clean", "light", "personal"]

features = [
    "widgets"
]

min_version = "0.123.0"

[author]
name = "Hannes Lehmann"
homepage = "https://hannes-lehmann.com/"

# If porting an existing theme
[original]
    author = "Adrián Moreno Peña"
    homepage = "https://www.adrianmoreno.info"
    repo = "https://github.com/zetxek/adritian-free-hugo-theme"