name: publish prod site

on:
  push:
    branches:
      - main
      - develop
      - feature/github-actions
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11 

      - name: Install postcss
        run: bun install postcss-cli

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.122.0'
          extended: true

      - name: Build
        run: hugo --minify --buildDrafts=true
      
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: website # e.g. 'my-project'
          directory: public # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        

